Remove previous/ version of module directory
When the policy is built with save-previous=true (see semanage.conf) the
previous version of store is saved in /var/lib/selinux/TYPE/previous directory.
This directory needs to be erased after build as it has no function for
packages.

Fixes:
Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/plautrba/rpmbuild/BUILDROOT/selinux-policy-3.14.4-4.fc31.x86_64
error: Installed (but unpackaged) file(s) found:
   /var/lib/selinux/targeted/previous/commit_num
   /var/lib/selinux/targeted/previous/file_contexts
   /var/lib/selinux/targeted/previous/file_contexts.homedirs
...